#
# More configuration examples at:
# http://jekyllrb.com/docs/configuration/
#
# Jekyll basic configurations
#

source:       ./_app
destination:  ./_site
timezone:     Asia/Hong_Kong
permalink:    /:title.html
markdown:     redcarpet
highlighter:  pygments

#
# Jekyll serve settings
#

port:         4321

#
# Jekyll build settings
#

future:       false

#
# Additional markdown settings
#

redcarpet:
  extensions:
    - footnotes
    - no_intra_emphasis
    - smart
    - space_after_headers
    - superscript
    - tables
